var config ={
    server: "https://quantridaihoc.edu.vn",
    serverChat: "https://api-apis.com",
    version: 1,
    objApi: {
        CM: '/csacmapi/api',
        SYS: '/csacmapi/api',
        CMS: '/cmsapi/api',
        DKH: '/dangkyhocapi/api',
        KHCT: '/kehoachchuongtrinhapi/api',
        KS: '/khaosatapi/api',
        KTX: '/kytucxaapi/api',
        NCKH: '/nckhapi/api',
        NS: '/nhansuapi/api',
        D: '/quanlydiemapi/api',
        SV: '/sinhvienapi/api',
        SMS: '/smsapi/api',
        TC: '/taichinhapi/api',
        TKGG: '/thongkegiogiangapi/api',
        L: '/luongapi/api',
        CC: '/chuyencanapi/api',
        HLTL: '/hoclaithilaiapi/api',
        RL: '/renluyenapi/api',
        XLHV: '/xulyhocvuapi/api',
        HDDT: '/hddtviettelapi/api',
        NH: '/nhaphocapi/api',
        TS: '/quanlytuyensinhapi/api',
        LVLA: '/luanvanluananapi/api',
        QLTTN: '/quanlythitracnghiemapi/api',
        HB: '/hocbongapi/api',
        TN: '/totnghiepapi/api',
        TT: '/tintucapi/api',
    }
}
module.exports = config;